version: '3.9'

services:
  postgres:
    image: postgres:17.4
    container_name: tech-select-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techselect
    ports:
      - "5556:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    container_name: tech-select-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9101"
    ports:
      - "9100:9000"
      - "9101:9101"
    volumes:
      - ./data/minio:/data